In [1]:
import itertools
import numpy as np

In [2]:
combinations = itertools.product([1, 2, 3, 4], repeat = 2)

In [3]:
combinations_list = list(combinations)
print(combinations_list)

[(1, 1), (1, 2), (1, 3), (1, 4), (2, 1), (2, 2), (2, 3), (2, 4), (3, 1), (3, 2), (3, 3), (3, 4), (4, 1), (4, 2), (4, 3), (4, 4)]


In [4]:
len(combinations_list)

16

In [5]:
combinations_array = np.asarray(combinations_list)

In [6]:
combinations_array

array([[1, 1],
       [1, 2],
       [1, 3],
       [1, 4],
       [2, 1],
       [2, 2],
       [2, 3],
       [2, 4],
       [3, 1],
       [3, 2],
       [3, 3],
       [3, 4],
       [4, 1],
       [4, 2],
       [4, 3],
       [4, 4]])

In [7]:
row_sums = combinations_array.sum(axis=1)

In [12]:
print(row_sums)

[2 3 4 5 3 4 5 6 4 5 6 7 5 6 7 8]


In [31]:
outcome, count = np.unique(row_sums, return_counts=True)

In [32]:
outcome

array([2, 3, 4, 5, 6, 7, 8])

In [16]:
count

array([1, 2, 3, 4, 3, 2, 1], dtype=int64)

In [17]:
p = count/len(combinations_list)

In [18]:
p

array([0.0625, 0.125 , 0.1875, 0.25  , 0.1875, 0.125 , 0.0625])

In [23]:
probability_array = np.asarray([outcome, count, p])

In [25]:
probability_array.T

array([[2.    , 1.    , 0.0625],
       [3.    , 2.    , 0.125 ],
       [4.    , 3.    , 0.1875],
       [5.    , 4.    , 0.25  ],
       [6.    , 3.    , 0.1875],
       [7.    , 2.    , 0.125 ],
       [8.    , 1.    , 0.0625]])

In [34]:
# shifting values of outcomes

outcome = outcome + 5
print(outcome)

[12 13 14 15 16 17 18]
